INSERT INTO odpt.station_timetable_object (
    station_timetable,
    train_type,
    departure_time,
    destination_station,
    is_origin
  )
VALUES 
  (
    'Keikyu.Main.AomonoYokocho.Inbound.Weekday',
    'Keikyu.AirportExpress',
    '09:44:00',
    '{Hokuso.Hokuso.ImbaNihonIdai}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '06:43:00',
    '{Keisei.Main.KeiseiUsui}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '08:43:00',
    '{Keisei.Main.KeiseiTsudanuma}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '09:03:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '09:59:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '10:23:00',
    '{Keisei.Main.KeiseiTsudanuma}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '20:53:00',
    '{Keisei.NaritaSkyAccess.ImbaNihonIdai}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '21:13:00',
    '{Keisei.Main.Sogosando}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '21:33:00',
    '{Keisei.Main.NaritaAirportTerminal1}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '21:46:00',
    '{Keisei.Main.KeiseiNarita}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '22:05:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '22:13:00',
    '{Keisei.Main.Sogosando}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '22:48:00',
    '{Keisei.Main.NaritaAirportTerminal1}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.SaturdayHoliday',
    'Keisei.Local',
    '23:37:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '06:39:00',
    '{Shibayama.Shibayama.ShibayamaChiyoda}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '07:27:00',
    '{Keisei.Chiba.ChibaChuo}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '08:21:00',
    '{Keisei.Main.KeiseiNarita}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '08:39:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '09:19:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '09:22:00',
    '{Hokuso.Hokuso.InzaiMakinohara}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '09:38:00',
    '{Keisei.Chihara.Chiharadai}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '09:45:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '11:22:00',
    '{Keisei.NaritaSkyAccess.ImbaNihonIdai}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '17:05:00',
    '{Keisei.Main.KeiseiNarita}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '18:05:00',
    '{Keisei.Main.KeiseiNarita}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '18:25:00',
    '{Keisei.Main.KeiseiOwada}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '19:23:00',
    '{Keisei.Main.KeiseiUsui}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '20:46:00',
    '{Keisei.Main.KeiseiSakura}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '21:34:00',
    '{Keisei.NaritaSkyAccess.ImbaNihonIdai}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '22:40:00',
    '{Keisei.Main.KeiseiTakasago}',
    null
  ),
  (
    'Keisei.Main.Aoto.Outbound.Weekday',
    'Keisei.Local',
    '23:49:00',
    '{Keisei.Main.KeiseiTsudanuma}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '06:48:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '07:05:00',
    '{Keikyu.Airport.HanedaAirportTerminal1and2}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '07:56:00',
    '{Keikyu.Airport.HanedaAirportTerminal1and2}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '08:15:00',
    '{Keisei.Main.KeiseiUeno}',
    true
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '08:26:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '08:37:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '09:26:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '10:04:00',
    '{Keikyu.Kurihama.Misakiguchi}',
    true
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '10:55:00',
    '{Keisei.Main.KeiseiUeno}',
    true
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '16:53:00',
    '{Toei.Asakusa.NishiMagome}',
    true
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '17:43:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '18:00:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '18:15:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '18:23:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '19:19:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '20:45:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '21:35:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '21:51:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '22:11:00',
    '{Keikyu.Kurihama.Misakiguchi}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '23:29:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.Weekday',
    'Keisei.Local',
    '23:53:00',
    '{Toei.Asakusa.Sengakuji}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.SaturdayHoliday',
    'Keisei.Local',
    '07:07:00',
    '{Toei.Asakusa.NishiMagome}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.SaturdayHoliday',
    'Keisei.Local',
    '21:34:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.SaturdayHoliday',
    'Keisei.Local',
    '21:50:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.SaturdayHoliday',
    'Keisei.Local',
    '22:15:00',
    '{Keisei.Main.KeiseiUeno}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.SaturdayHoliday',
    'Keisei.Local',
    '22:35:00',
    '{Keikyu.Kurihama.Miurakaigan}',
    null
  ),
  (
    'Keisei.Main.KeiseiTakasago.Inbound.SaturdayHoliday',
    'Keisei.Local',
    '23:53:00',
    '{Toei.Asakusa.Sengakuji}',
    null
  );